name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Preparing tarantool container
      run: |
        docker run --name mytarantool -d -p 3301:3301 tarantool/tarantool:latest
    - name: Run unit tests
      run: |
        python ./01_advanced_basics/homework/test_log_analyzer.py
        python ./05_OOP/homework/test_api.py
        python ./05_OOP/homework/test_scoring.py